# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
cmkr-include = ["cmake/cmkr.toml"]

[project]
name = "remill-workshop"

[variables]
CMAKE_MODULE_PATH = "${CMAKE_SOURCE_DIR}/cmake"
GFLAGS_USE_TARGET_NAMESPACE = true

[find-package.Z3]
[find-package.LLVM-Wrapper]
[find-package.remill]

[template.remill]
type = "executable"
compile-features = ["cxx_std_17"]
link-libraries = [
    "LLVM-Wrapper",
    "remill",
    "remill_settings",
]

[target.hello]
type = "remill"
sources = ["src/hello.cpp"]

[target.remill-lift]
type = "remill"
sources = ["src/remill-lift.cpp"]
