# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "remill-workshop"

[variables]
CMAKE_MODULE_PATH = "${CMAKE_SOURCE_DIR}/cmake"
GFLAGS_USE_TARGET_NAMESPACE = true
CMAKE_CXX_FLAGS_DEBUG = "-O0 -gfull"

[template.llvm-tool]
type = "executable"
compile-features = ["cxx_std_20"]
link-libraries = ["LLVM-Wrapper", "remill", "remill_settings"]

[find-package.Z3]
[find-package.LLVM-Wrapper]
[find-package.remill]
[find-package.LIEF]

# Compile the helpers
[subdir.helpers]

[target.hello]
type = "llvm-tool"
sources = ["src/hello.cpp"]

[target.remill-lift]
type = "llvm-tool"
sources = ["src/remill-lift.cpp"]
link-libraries = ["LIEF::LIEF"]

[target.api-basics]
type = "llvm-tool"
sources = ["src/api-basics.cpp"]

[target.bc-tool]
type = "llvm-tool"
sources = ["src/bc-tool.cpp"]

[target.bc-stats]
type = "llvm-tool"
sources = ["src/bc-stats.cpp"]

[target.bc-demangle]
type = "llvm-tool"
sources = ["src/bc-demangle.cpp"]
