# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "remill-workshop"

[variables]
CMAKE_MODULE_PATH = "${CMAKE_SOURCE_DIR}/cmake"
GFLAGS_USE_TARGET_NAMESPACE = true

[find-package.Z3]
[find-package.LLVM-Wrapper]
[find-package.remill]

[template.llvm-tool]
type = "executable"
compile-features = ["cxx_std_17"]
link-libraries = ["LLVM-Wrapper", "remill", "remill_settings"]

[target.hello]
type = "llvm-tool"
sources = ["src/hello.cpp"]

[target.remill-lift]
type = "llvm-tool"
sources = ["src/remill-lift.cpp"]

[target.process-module]
type = "llvm-tool"
sources = ["src/process-module.cpp"]
